steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
  - '-c'
  - 'gcloud beta deploy releases create rel-$(date +%y%m%d-%s) --delivery-pipeline=ns-test --region=us-central1  --images=nginx=us.gcr.io/dc-hughes-anthos-migration/homeapp:v1.11'
