apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: ns-test
description: homeapp delivery pipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles:
   - dev
   - qa
 - targetId: qa
   profiles:
   - qa
   - dev
 - targetId: prd
   profiles:
   - prod
   - dev
   - qa
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: dev
description: dev cluster
gke:
 cluster: projects/dc-hughes-anthos-migration/locations/us-central1-c/clusters/dev
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: qa
description: qa cluster
gke:
 cluster: projects/dc-hughes-anthos-migration-two/locations/us-central1-c/clusters/qa
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: prd
description: prd cluster
#requireApproval: true
gke:
 cluster: projects/dc-hughes-ant-migration-three/locations/us-central1-c/clusters/prod
