---
apiVersion: v1
kind: Pod
metadata:
 name: nginx
 labels:
  app: sampleapp
spec:
 containers:
 - name: nginx
   image: us.gcr.io/dc-hughes-anthos-migration/abc:25
   ports:
   - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: myweb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sampleapp
---
  
