---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: sampleapp
 labels:
  app: sampleapp
spec:
 selector:
  matchLabels:
   app: sampleapp
 replicas: 1
 template:
  metadata:
   labels:
    app: sampleapp
  spec:
   containers:
   - name: nginx
     image: nginx
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: mysvc
spec:
 type: LoadBalancer
 selector:
  app: sampleapp
 ports:
 - port: 8080
   targetPort: 80
   protocol: TCP
---
