apiVersion: skaffold/v2beta16
kind: Config
deploy:
 kubectl:
  manifests:
   - myapp.yaml
  flags:
   global:
   - --namespace=default
profiles:
- name: dev
  patches:
  - op: replace
    path: /deploy/kubectl/flags/global/0
    value: --namespace=test
- name: qa
  patches:
  - op: replace
    path: /deploy/kubectl/flags/global/0
    value: --namespace=test1
- name: prod
  patches: 
  - op: replace
    path: /deploy/kubectl/flags/global/0
    value: --namespace=test2
